### ISSUE TITLE
Hard to distinguish new/updated libraries

### ISSUE THREAD

**Issue by Talkless** [cornelius/inqlude-data#103]
Hi,

I come to inqlude.org time to time to check what's new and cool available, but it is actually hard to notice new packages from plain list. There is `Last updated on 2016-07-13` on bottom of the page, but what exactly has changed?

It would be nice to have possibility to sort list by add/update dates using buttons, or having different views (pages) for sorted lists.

**Comment by cornelius** [comment]
You are right. There is work going on as part of the Summer of Code to fix this issue.

We already have an issue at https://github.com/cornelius/inqlude/issues/22. I'll close this one, let's track progress over there.
